### ISSUE TITLE
Implementar los casos de uso

### ISSUE THREAD

**Issue by neftalito** [Fabandnef/SGE#57]
- [x] Crear Usuario
- [x] Eliminar Usuario
- [x] Modificar Usuario
- [x] Listar Usuario
- [x] Editar Perfil
- [x] Editar Permisos
- [x] Registro de Usuario
- [x] Inicio de sesión de Usuario
- [x] Cierre de sesión de Usuario
- [x] Listar expedientes
- [x] Crear expediente
- [x] Modificar expediente
- [x] Borrar expediente
- [x] Listar tramites
- [x] Crear tramite
- [x] Modificar tramite
- [x] Eliminar tramite

**Comment by fabriziogirardi** [comment]
@neftalito voy a terminar el listar expedientes y el dialog de eliminar expedientes. Abro issue para eso, y rama.
